---
language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: gqprf18LRpjwGmSt3sWUJy8ZeJkgIFRg697QT5N0JtVsqUD/9Gr2w/GzmUaq5NLLMEsKie930JMheiQfiPdlByu1LygYtrSZVfivn57ssrWZiCqMlqFQE3ZdwzPiLguWgjSAMFL3KKxvRdzIfWn8oKajez4EIf0yaijJT6sNoF17JEU3vzf76/oSncj+kim9j1Z3rbjrKaIypLt4D2IPn5XfTPXNd0eueNFnLvWE7yuUflehiKJZjVWNA5NNrT6VRXe0wGoavOMibajLLf/esDbedhlX7Cvbo7Z111FVw56LrGSTWG7zz6F1qGkhoVPb0MqWUPBz5e2CF8mZ9qjaoy8qD2ptPMfd64SGvDitQNg6zgzU4SaldcgdnKPL6NGUjkKB581JgJATpG7wmB4XS6Kp40XYiaXvpg2AtS9tjcbO89qMKKhN2fgxn8RylelKUiue1KtGP16LjNEpCogcMUqQiMj7BmXQKBn6AecfyRTvZweFJkWGj99Jw4S1M1ZKgIUcG+q1uSMTWYR1x+fZnDQQ76cOqiNXDVYCjBHe8mawEkrIcwWNc8L9ArU/pohCOBZdV2k2223GhlIYoVnUD3/XjWrgsrKL7GrM9GCuYd0rBZPO3ReNVhD4U90OjEg1BeyMY6c0yBOyR4AJBK1a6HLsGAvEiMjDuGT616bmLUw=
